language: node_js
sudo: false
node_js:
  - '6'
  - '7'
  - '8'
cache: yarn
script:
  - npm install chat-engine
  - npm install -g express
  - npm install
  - gulp patch_server
  - node ./node_modules/chat-engine/server.js &
  - gulp test
  - gulp restore_server
after_success:
  - npm install codecov codacy-coverage